backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {labal: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/oferta/index.md"
        label: "Oferta"
        name: "oferta"
        fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "oferta-page"}
        - {label: "Title", name: "title", widget: "string"}
        - {labal: "Featured Image", name: "thumbnail", widget: "image"}
        - {label: "Description", name: "description", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}  
      - file: "src/pages/kontakt/index.md"
        label: "Kontakt"
        name: "kontakt"
        fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "kontakt-page"}
        - {label: "Title", name: "title", widget: "string"}
        - {labal: "Featured Image", name: "thumbnail", widget: "image"}
        - {label: "Description", name: "description", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/omnie/index.md"
        label: "Omnie"
        name: "omnie"
        fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "omnie-page"}
        - {label: "Title", name: "title", widget: "string"}
        - {labal: "Featured Image", name: "thumbnail", widget: "image"}
        - {label: "Description", name: "description", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/referencje/index.md"
        label: "Omnie"
        name: "omnie"
        fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "referencje-page"}
        - {label: "Title", name: "title", widget: "string"}
        - {labal: "Featured Image", name: "thumbnail", widget: "image"}
        - {label: "Description", name: "description", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
          